  version: 2.1
  orbs:
    browser-tools: circleci/browser-tools@1.1.0
  jobs:
    test:
      working_directory: ~/project
      docker:
          - image: cimg/node:16.13.1-browsers
      steps:
          - browser-tools/install-chrome
          - browser-tools/install-chromedriver
          - run:
              name: Check browser install
              command: |
                google-chrome --version
                chromedriver --version

          # Checkout the code from the branch into the working_directory
          - checkout
          # Log the current branch
          - run:
              name: Show current branch
              command: echo ${CIRCLE_BRANCH}
          # Restore local dependencies from cache
          - restore_cache:
              keys:
              - v1-dependencies-{{ checksum "package-lock.json" }}
              - v1-dependencies-
          # Install project dependencies
          - run:
              name: Install local dependencies
              command: npm install
          # Cache local dependencies if they don't exist
          - save_cache:
              key: v1-dependencies-{{ checksum "package-lock.json" }}
              paths:
                  - node_modules
          # Test the source code
          - run:
              name: Testing
              command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    deploy:
      working_directory: ~/project
      docker:
          - image: cimg/node:16.13.1
      steps:
          # Checkout the code from the branch into the working_directory
          - checkout
          # Log the current branch
          - run:
              name: Show current branch
              command: echo ${CIRCLE_BRANCH}
          # Restore local dependencies from cache
          - restore_cache:
              keys:
              - v1-dependencies-{{ checksum "package-lock.json" }}
              - v1-dependencies-
          # Install project dependencies
          - run:
              name: Install local dependencies
              command: npm install
          # Cache local dependencies if they don't exist
          - save_cache:
              key: v1-dependencies-{{ checksum "package-lock.json" }}
              paths:
                  - node_modules
          - run:
              name: Build app env ${CIRCLE_BRANCH}
              command: npm run build:${CIRCLE_BRANCH}
          # - run:
          #     name: Install firebase-cli
          #     command: npm install -g firebase-tools
          - run:
              name: Deploy app to Firebase
              command: npm run deploy -- --token "${FIREBASE_TOKEN}"
  workflows:
        # the test workflow
    # test_workflow:
    #   jobs:
    #     - test:
    #         filters:
    #             branches:
    #                 only:
    #                     - develop
    #                     - staging
    #                     - main
    #                     - acceptance
    test-and-deploy:
      jobs:
        - test:
            filters:
                branches:
                    only:
                        - develop
                        - staging
                        - main
                        - acceptance
        - deploy:
            context:
              - car_app
            requires:
              - test
            filters:
                branches:
                    only:
                        - staging
                        - main
                        - acceptance
